---
- hosts: all   
  become: yes 
  tasks: 
  - name: install tomcat9 on ubunt [in shell apt-get update & apt-get install tomcat9 -y]
    ansible.builtin.apt: 
      update_cache: yes
      name: tomcat9 
      state: present  